server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    #url中database为对应的数据库名称
    url: jdbc:mysql://120.79.224.47:3306/aiduigui?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.aiduigui.api.server.entity

#showSql
logging:
  level:
    com.aiduigui.api.server.mapper: debug
